### ISSUE TITLE
jsonapi-serializer migration

### ISSUE THREAD

**Issue by jbailey4** [IanVS/sails-hook-jsonapi#6]
Currently the code in responses/ok.js uses the outdated, pre v2.1 jsonapi-serializer api, this results in an error stating `JSONAPISerializer is not a function` when serializing the response data.  
Checkout the [migration guide](https://github.com/SeyZ/jsonapi-serializer/wiki/Migrate-from-2.0-to-3.0). The fix seems easy and would be glad to submit a PR.

**Comment by jbailey4** [comment]
Whoops, just noticed the updated code is in master and hasn't been tagged for a release yet. No need for a PR.

**Comment by IanVS** [comment]
v0.0.3 is released, thanks for the prompt. :smiley:

**Comment by jbailey4** [comment]
:+1: Thanks for starting this project, much needed in Sails (especially when using with Ember). If you ever need any help with this project let me know.

**Comment by IanVS** [comment]
@jbailey4 help would be awesome.  I've stopped using Sails and Ember, so any progress on this project will need to come from other contributors like you.  I'm happy to merge PRs or turn over the project entirely to anyone who wants to step up and take it over.
